# Write down config entries differing from config.default.yaml
run: {}

enable:
  retrieve_databundle: false # Recommended 'true', for the first run. Otherwise data might be missing.
  retrieve_databundle_sector: false
  retrieve_cost_data: true # true: retrieves cost data from technology data and saves in resources/costs.csv, false: uses cost data in data/costs.csv
  download_osm_data: true # If 'true', OpenStreetMap data will be downloaded for the above given countries
  build_natura_raster: false # If True, then an exclusion raster will be build
  build_cutout: false
  # If "build_cutout" : true, then environmental data is extracted according to `snapshots` date range and `countries`
  # requires cds API key https://cds.climate.copernicus.eu/api-how-to
  # More information https://atlite.readthedocs.io/en/latest/introduction.html#datasets
  progress_bar: true # show progress bar during downloading routines and other long-running tasks

scenario:
  clusters: [250]
  opts: [6h]

snapshots:
  start: "2013-01-01"
  end: "2014-01-01"
  inclusive: "left"

load_options:
  ssp: "ssp2-2.6"
  weather_year: 2013
  prediction_year: 2030
  scale: 1.6818
  disaggregation:
    method: geospatial
    geospatial:
      source: "resources/shapes/gadm_shapes.geojson"
      scaling: "subregional"

build_shape_options:
  gadm_layer_id: 2 # GADM level area used for the gadm_shapes. Codes are country-dependent but roughly: 0: country, 1: region/county-like, 2: municipality-like
  simplify_tolerance: 0.01 # Default value is 0.01, higher the value more is the simplification of the GADM shapes
  simplify_gadm: true # When true, shape polygons are simplified else no
  minarea: 0.01 # Minimum area of polygons to be retained in GADM shapes after simplification, in square degrees. Polygons with area smaller than this value will be removed
  update_file: false # When true, all the input files are downloaded again and replace the existing files
  out_logging: true # When true, logging is printed to console
  year: 2020 # reference year used to derive shapes, info on population and info on GDP
  nprocesses: 3 # number of processes to be used in build_shapes
  worldpop_method: "standard" # "standard" pulls from web 1kmx1km raster, "api" pulls from API 100mx100m raster,
  # false (not "false") no pop addition to shape which is useful when generating only cutout
  gdp_method: "standard" # "standard" pulls from web 1x1km raster, false (not "false") no gdp addition to shape which useful when generating only cutout
  contended_flag: "set_by_country" # "set_by_country" assigns the contended areas to the countries according to the GADM database, "drop" drops these contended areas from the model

electricity:
  extendable_carriers:
    Generator: [solar, onwind, offwind-ac, offwind-dc, nuclear]
    StorageUnit: [battery, H2]
    Store: []
    Link: []
  powerplants_filter: "(DateOut >= 2060 or DateOut != DateOut) and (DateIn <= 2060 or DateIn != DateIn)"
  
  max_hours:
    battery: 4
    H2: 168
    PHS: 10  

  estimate_renewable_capacities:
    stats: "irena" 
    year: 2023

cluster_options:
  alternative_clustering: true # "False" use Voronoi shapes, "True" use GADM shapes
  simplify_network:
    to_substations: false # network is simplified to nodes with positive or negative power injection (i.e. substations or offwind connections)
    algorithm: kmeans # choose from: [hac, kmeans]
    feature: solar+onwind-time # only for hac. choose from: [solar+onwind-time, solar+onwind-cap, solar-time, solar-cap, solar+offwind-cap] etc.
    exclude_carriers: []
    remove_stubs: true
    remove_stubs_across_borders: false
    p_threshold_drop_isolated: 0. # [MW] isolated (sub)networks or nodes are being discarded if total mean power is below the specified threshold
    p_threshold_merge_isolated: 0. # [MW] isolated (sub)networks or nodes are being merged into a single isolated bus if total mean power is below the specified threshold
    s_threshold_fetch_isolated: false # [-] a share of the national load for merging an isolated network into a backbone network
  cluster_network:
    algorithm: kmeans
    feature: solar+onwind-time
    exclude_carriers: []

solving:
  solver:
    gurobi_hpc_tunnel:
      use_tunnel: True
      tunnel_port: 27000
      timeout_s: 15
      login_node: "03"
      gurobi_home: "/p/projects/rd3mod/gurobi1103/linux64"
      license_path: "/p/projects/rd3mod/gurobi_rc/gurobi.lic"
      verbose: "1"
      timeout: "10"
      ssl_cert: "/p/projects/rd3mod/ssl/ca-bundle.pem_2022-02-08"
      grb_cafile: "/p/projects/rd3mod/ssl/ca-bundle.pem_2022-02-08"